version: '3.8'

services:
  postgres:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: raffleDES
    container_name: raffleDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hbracho55@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - "5050:80"
    depends_on:
      - postgres
